export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const RESET_CART = "RESET_CART";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const SAVE_BILLING_INFO = "SAVE_BILLING_INFO";

export const CHANGE_QUANTITY_CART = "CHANGE_QUANTITY_CART";

export const GET_CART_ITEMS = "GET_CART_ITEMS";
