export const GET_VARIETY_DETAILS_REQUEST = 'GET_VARIETY_DETAILS_REQUEST';
export const GET_VARIETY_DETAILS_SUCCESS = 'GET_VARIETY_DETAILS_SUCCESS';
export const GET_VARIETY_DETAILS_FAILURE = 'GET_VARIETY_DETAILS_FAILURE';
