export const ANIMAL_TYPE_LOAD_REQUEST = "ANIMAL_TYPE_LOAD_REQUEST";
export const ANIMAL_TYPE_LOAD_SUCCESS = "ANIMAL_TYPE_LOAD_SUCCESS";
export const ANIMAL_TYPE_LOAD_FAIL = "ANIMAL_TYPE_LOAD_FAIL";
export const ANIMAL_TYPE_LOAD_RESET = "ANIMAL_TYPE_LOAD_RESET";