export const DAILY_ESSENTIALS_TYPE_LOAD_REQUEST = "DAILY_ESSENTIALS_TYPE_LOAD_REQUEST";
export const DAILY_ESSENTIALS_TYPE_LOAD_SUCCESS = "DAILY_ESSENTIALS_TYPE_LOAD_SUCCESS";
export const DAILY_ESSENTIALS_TYPE_LOAD_FAIL = "DAILY_ESSENTIALS_TYPE_LOAD_FAIL";
export const DAILY_ESSENTIALS_TYPE_LOAD_RESET = "DAILY_ESSENTIALS_TYPE_LOAD_RESET";