export const MEDICAL_CARE_TYPE_LOAD_REQUEST = "MEDICAL_CARE_TYPE_LOAD_REQUEST";
export const MEDICAL_CARE_TYPE_LOAD_SUCCESS = "MEDICAL_CARE_TYPE_LOAD_SUCCESS";
export const MEDICAL_CARE_TYPE_LOAD_FAIL = "MEDICAL_CARE_TYPE_LOAD_FAIL";
export const MEDICAL_CARE_TYPE_LOAD_RESET = "MEDICAL_CARE_TYPE_LOAD_RESET";