export const TREATMENT_TYPE_LOAD_REQUEST = "TREATMENT_TYPE_LOAD_REQUEST";
export const TREATMENT_TYPE_LOAD_SUCCESS = "TREATMENT_TYPE_LOAD_SUCCESS";
export const TREATMENT_TYPE_LOAD_FAIL = "TREATMENT_TYPE_LOAD_FAIL";
export const TREATMENT_TYPE_LOAD_RESET = "TREATMENT_TYPE_LOAD_RESET";